### ISSUE TITLE
Uploading a large file times out after ~20mins

### ISSUE THREAD

**Issue by Sankara-Jefferson** [web3-storage/w3up#1290] opened 2024-01-30 00:16 UTC
User managed to upload 3 smaller files < 1GB but gets timeouts while uploading a 2GB file. he tried LTS version of node js to no avail.

```
❯ w3 up Homicidio.parquet.zip
  1 file 2.0GB
⠴ Storing 27%node:internal/deps/undici/undici:12344
    Error.captureStackTrace(err, this);
          ^

TypeError: fetch failed
    at node:internal/deps/undici/undici:12344:11
    at async retry.retries (file:///opt/homebrew/lib/node_modules/@web3-storage/w3cli/node_modules/@web3-storage/upload-client/dist/src/store.js:82:25)
    at async RetryOperation._fn (file:///opt/homebrew/lib/node_modules/@web3-storage/w3cli/node_modules/p-retry/index.js:55:13) {
  cause: HeadersTimeoutError: Headers Timeout Error
      at Timeout.onParserTimeout [as callback] (node:internal/deps/undici/undici:8851:32)
      at Timeout.onTimeout [as _onTimeout] (node:internal/deps/undici/undici:6893:17)
      at listOnTimeout (node:internal/timers:573:17)
      at process.processTimers (node:internal/timers:514:7) {
    code: 'UND_ERR_HEADERS_TIMEOUT'
  },
  attemptNumber: 4,
  retriesLeft: 0
}

Node.js v20.11.0

pball@porky:~/tmp/CO-data 20m24s408ms
❯
```

**Comment by ianconsolata** [comment] 2024-02-05 18:31
@Sankara-Jefferson can you run `w3 --version` and share the output? I was experiencing a similar issue that was fixed in 7.0.3.

**Comment by Sankara-Jefferson** [comment] 2024-02-05 18:44
@ianconsolata , its on Patrick's machine. Here is the output.

```
pball@porky:~/dotfiles on main *​ 1s870ms
❯ w3 --version
w3, 7.5.0
```

**Comment by travis** [comment] 2024-02-05 19:12
Thanks for the report @Sankara-Jefferson! From the stack trace this looks like it was an error `PUT`ing bytes to S3, which suggests it may have been either a network issue or an S3 issue - is it happening consistently or was this just a one-off failure?

**Comment by travis** [comment] 2024-02-05 19:14
Also, would it be feasible to share `Homicidio.parquet.zip` ? If this is a consistent failure it would be very helpful to have the file so we can fix whatever's going wrong.

**Comment by Sankara-Jefferson** [comment] 2024-02-05 21:15
@travis it was consistent. Here is the file. 

https://drive.google.com/file/d/1iHnSH_4KOG9fle_pBjEK82ueUhgDT4m9/view

**Comment by travis** [comment] 2024-02-05 22:37
thank you! will dig into this asap

**Comment by travis** [comment] 2024-02-06 00:06
Interesting - I was able to upload this successfully: 

<img width="601" alt="Screenshot 2024-02-05 at 4 01 53 PM" src="https://github.com/web3-storage/w3up/assets/1113/d83dd9ac-d686-4b44-b8bc-3ec4571b3b41">

It went pretty quickly, but I'm also hardwired into a 1gbps fiber connection.

Because of the way w3up works I suspect this may succeed for you now - since we already have the bits (from my upload) your upload will just essentially just be registering it as your upload - the magic of content addressing!

I'd love to know if this is working now on your end - this has opened up a couple lines of investigation here, but we may not be able to reproduce the failure at this point, in which case I'd like to close this issue.

**Comment by travis** [comment] 2024-02-06 00:09
Oh, and apologies, I didn't read your last message closely enough - glad to hear it finally worked!

One of the lines of investigation we're digging into is looking at the S3 upload timeouts - they aren't currently configurable but we are looking at raising them. Making them configurable is a good thought - will look into whether that's something that would make sense to expose to the end user.

Sounds like this is good to close out! Please feel free to reopen if there's more to chat about! Thanks again for the bug report!

**Closed by travis** 2024-02-06 00:09 UTC

**Comment by Sankara-Jefferson** [comment] 2024-02-06 16:51
@travis thank you.
